config/routes.rb
Rails.application.routes.draw do
  # Front-End
  root "default#index"

  # Account Management
  get '/account', to: "account#index"
  get '/account/detail', to: "account#detail"
  get '/account/billing', to: "account#billing"
  get '/account/password', to: "account#password"
  get '/account/notification', to: "account#notification"

  get '/account/transaction', to: "account#transaction"
  get '/account/invoice', to: "account#invoice"

  get '/account/subscription', to: "account#subscription"
  post '/account/subscription/add', to: "account#subscriptionAdd"

  get '/account/subscription/upgrade', to: "account#subscriptionUpgrade"

  patch '/account/detail/update', to: "account#detailUpdate"
  post  '/account/password/update', to: "account#passwordUpdate"
  patch '/account/notification/update', to: "account#notificationsUpdate"

  get '/account/billing/deposit', to: "account#deposit"
  post '/account/billing/depositCharge', to: "account#depositCharge"
  
  get '/account/payment', to: "account#payment"
  get '/account/payment/charge', to: "account#paymentCharge"

  post '/account/payment/verify', to: "account#paymentVerify"
  post '/account/payment/remove', to: "account#paymentRemove"

  post '/users/_session?destroy', to: "default#sessions"

  # Reseller Management
  get '/reseller', to: "reseller#index"
  get '/reseller/customer', to: "reseller#customer"
  get '/reseller/customer/create', to: "reseller#customerCreate"
  post '/reseller/customer/add', to: "reseller#customerAdd"
  get '/reseller/customer/:username', to: "reseller#customerDetail"
  get '/reseller/customer/:username/billing', to: "reseller#customerBilling"
  get '/reseller/customer/:username/transaction', to: "reseller#customerTransactions"
  get '/reseller/customer/:username/edit', to: "reseller#customerEdit"
  patch '/reseller/customer/update', to: "reseller#customerUpdate"
  delete '/reseller/customer/:username', to: "reseller#customerDelete"

  get '/reseller/package', to: "reseller#package"
  get '/reseller/package/create', to: "reseller#packageCreate"
  post '/reseller/package/add', to: "reseller#packageAdd"

  get '/reseller/subscription', to: "reseller#subscription"

  get '/reseller/configuration', to: "reseller#configuration"
  patch '/reseller/configuration/update', to: "reseller#resellerUpdate"

  # Content Delivery Network(CDN)
  get '/cdn', to: "delivery#delivery"
  get '/cdn/:propertyId/:dtype', to: "delivery#deliveryDetail"
  get '/cdn/:propertyId/:dtype/reports', to: "delivery#deliveryReport"
  get '/cdn/:propertyId/:dtype/logs', to: "delivery#deliveryLog"

  get '/cdn/:propertyId/:dtype/policies/:ptype', to: "delivery#deliveryPolicy"

  get '/cdn/:propertyId/:dtype/policies/:ptype/add', to: "delivery#deliveryAddPolicy"

  post '/cdn/:propertyId/:dtype/policies/:ptype/', to: "delivery#deliveryUpdatePolicy"

  post '/cdn/policies/create', to: "delivery#deliveryCreatePolicy"
  delete '/cdn/:propertyId/:dtype/policies/:ptype/:policyId', to: "delivery#deliveryDeletePolicy"

  get '/cdn/create', to: "delivery#deliveryCreate"
  post '/cdn/add', to: "delivery#deliveryAdd"

  get '/cdn/:propertyId/:dtype/edit', to: "delivery#deliveryEdit"

  put '/cdn/update', to: "delivery#deliveryUpdate"

  post '/cdn/:propertyId/:dtype/stop', to: "delivery#deliveryStop"
  post '/cdn/:propertyId/:dtype/start', to: "delivery#deliveryStart"
  post '/cdn/:propertyId/:dtype/delete', to: "delivery#deliveryDelete"

  # API
  namespace :api do
    scope 'v1.1', as: :v1 do
      get '/', to: "v1#index"

      # Web Acceleration Service
      get '/listDelivery', to: "v1#listDelivery"

      # File Download Acceleration
      get '/listDownload', to: "v1#listDownload"

      # Runtime Background
      get '/customerDelivery', to: "v1#customerDelivery"
      get '/customerDownload', to: "v1#customerDownload"

      post '/customerVolume', to: "v1#customerVolume"
      post '/customerStorage', to: "v1#customerStorage"

      # Check CNAME
      get '/checkCname', to: "v1#checkCname"

      # Check SSID
      post '/checkSSID', to: "v1#checkSSID"
    end
  end

  # Authenticator
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", confirmations: 'users/confirmations' }

  # Runtime Background
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  mount Sidekiq::Web, at: '/sidekiq'

  # existing paths
  match '/errors', to: "default#bugs", via: :all
  match '*path' => 'default#errors', via: :all
end

app/controllers/delivery_controller.rb
class DeliveryController < ApplicationController
	require 'will_paginate/array'
	before_action :verify_subscription, except: [:deliveryStop]

	# Set Request Method
	before_action :post_method, only: [:deliveryAdd, :deliveryReport, :deliveryLog, :deliveryCreatePolicy]
	before_action :get_method, only: [:delivery, :deliveryDetail, :deliveryEdit, :deliveryPolicy]
	before_action :put_method, only: [:deliveryUpdate, :deliveryStop, :deliveryStart, :deliveryUpdatePolicy]
	before_action :delete_method, only: [:deliveryDelete, :deliveryDeletePolicy]

	# Set End Point Request
	before_action :cdn_endpoint, only: [:delivery, :deliveryDetail, :deliveryReport, :deliveryAdd, :deliveryLog, :deliveryEdit, :deliveryUpdate, :deliveryStop, :deliveryStart, :deliveryDelete, :deliveryPolicy, :deliveryCreatePolicy, :deliveryEditPolicy, :deliveryUpdatePolicy]

	def delivery
		@domainList = []

		if params[:per_page].nil?
	  	params[:per_page] = 10
	  end

		@requestURI = "/v1.0/customers/#{current_user.uuid}/domains"
		@delivery = JSON.parse(RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest())

		@delivery.each do |delivery|
			@domainList << delivery
		end

		@requestURI = "/v1.0/customers/#{current_user.uuid}/filedownloads"
		@download = JSON.parse(RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest())

		@download.each do |download|
			@domainList << download
		end

		@domainItems = @domainList.paginate(:page => params[:page], :per_page => params[:per_page])
	rescue SocketError => e
  	flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
  end

  def deliveryDetail
  	if params[:dtype] == "d"
	  	@requestURI = "/v1.0/domains/#{params[:propertyId]}"
  	elsif params[:dtype] == "f"
	  	@requestURI = "/v1.0/filedownloads/#{params[:propertyId]}"
		end

		@response = JSON.parse(RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest())
	rescue SocketError => e
  	flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
  end

  def deliveryEdit
  	if params[:dtype] == "d"
	  	@requestURI = "/v1.0/domains/#{params[:propertyId]}"
  	elsif params[:dtype] == "f"
	  	@requestURI = "/v1.0/filedownloads/#{params[:propertyId]}"
		end

		@response = JSON.parse(RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest())
	rescue TypeError => e
    flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
	rescue SocketError => e
  	flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
  end

  def deliveryReport
  	if params[:domain].present?
	  	endTime = Time.now.utc 
		  @endTime = endTime.strftime("%Y-%m-%dT%H:%M:00Z")

	  	if params[:range].nil?
		    startTime = endTime - 4.hours
		  elsif params[:range] == "1"
		  	startTime = endTime - 1.hours
		  elsif params[:range] == "8"
		  	startTime = endTime - 8.hours
		  elsif params[:range] == "24"
		  	startTime = endTime - 1.days
		  end

		  @startTime = startTime.strftime("%Y-%m-%dT%H:%M:00Z")

	  	@requestURI = "/v1.1/report/volume"
			@requestBody = "{\"domains\":[\"#{params[:domain]}\"],\"startTime\":\"#{@startTime}\",\"endTime\":\"#{@endTime}\",\"fillFixedTime\":\"true\",\"interval\":\"#{@interval}\"}"
			@traffic = JSON.parse(RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest())

			@timestamp = []
			@trafficValue = []
			@totalBandwidth = 0
			@totalValues = 0

			@traffic.each do |item|
				item["volumes"].each do |stamp|
					@timestamp << stamp["timestamp"]
					@trafficValue << stamp["value"]
				end
			end

			@requestURI = "/v1.0/report/origin_request_number"
			@requestBody = "{\"domains\":[\"#{params[:domain]}\"],\"startTime\":\"#{@startTime}\",\"endTime\":\"#{@endTime}\",\"fillFixedTime\":\"true\",\"interval\":\"#{@interval}\"}"
			@request = JSON.parse(RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest())

			@requestValue = []

			@request.each do |item|
				item["originReqNums"].each do |stamp|
					@requestValue << stamp["value"]
				end
			end
			
			@bandwidthValue = []

			@requestURI = "/v1.0/report/origin_bandwidth"
			@requestBody = "{\"domains\":[\"#{params[:domain]}\"],\"startTime\":\"#{@startTime}\",\"endTime\":\"#{@endTime}\",\"fillFixedTime\":\"true\",\"interval\":\"#{@interval}\"}"
			@bandwith = JSON.parse(RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest())

			@bandwith.each do |item|
				item["originBandwidths"].each do |stamp|
					@totalValues += 1
					@totalBandwidth += stamp["value"]
					@bandwidthValue << stamp["value"]
				end
			end

			@maxBandwidth = @bandwidthValue.map(&:to_i).max
			
			@avgBandwidth = @totalBandwidth/@totalValues
		else
			redirect_to cdn_path
		end
	rescue TypeError => e
    flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
	rescue SocketError => e
  	flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
  end

  def deliveryLog
  	if params[:domain].present? || params[:for].present?
	  	endTime = Time.now.utc 
		  @endTime = endTime.strftime("%Y-%m-%dT%H:%M:%SZ")

	  	if params[:range].nil?
		    startTime = endTime - 4.hours
		  elsif params[:range] == "1"
		  	startTime = endTime - 1.hours
		  elsif params[:range] == "8"
		  	startTime = endTime - 8.hours
		  elsif params[:range] == "24"
		  	startTime = endTime - 1.days
		  end

		  @startTime = startTime.strftime("%Y-%m-%dT%H:05:00Z")

		  if params[:domain].nil?
		  	params[:domain] = params[:for]
		  end

		  if params[:per_page].nil?
		  	params[:per_page] = 10
		  end

	  	@requestURI = "/v1.1/log/list"
			@requestBody = "{\"domains\":[\"#{params[:domain]}\"],\"startTime\":\"#{@startTime}\",\"endTime\":\"#{@endTime}\"}"
			@response = JSON.parse(RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest())

			@timestamps = []
			@items = []

			@response.each do |response|
				response["logs"].each do |log|
					@timestamps << log["timestamp"]
					log["values"].each do |item|
						@items << item
					end
				end
			end

			@logItems = @timestamps.zip(@items).paginate(:page => params[:page], :per_page => params[:per_page])
		else
			redirect_to cdn_path
		end
	rescue TypeError => e
    flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
	rescue SocketError => e
  	flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
  end

  def deliveryAdd
  	if params[:ftpPassword].nil?
	  	@requestURI = "/v1.0/domains"
			@requestBody = "{\"name\":\"#{params[:deliveryUrl]}\",\"customerId\":#{current_user.uuid},\"originUrl\":\"#{params[:originUrl]}\",\"streamingService\":#{params[:streamingService]},\"active\":true}"
		else
			if params[:ftpPassword] != params[:ftpPasswordConfirm]
	      flash[:confirm_notice] = "Error! Confirm password not match, please check again."
	      redirect_back(fallback_location: root_path)
	      return
	    else
	    	@requestURI = "/v1.0/filedownloads"
				@requestBody = "{\"name\":\"#{params[:deliveryUrl]}\",\"customerId\":#{current_user.uuid},\"originUrl\":\"\",\"ftpPassword\":\"#{params[:ftpPassword]}\",\"streamingService\":#{params[:streamingService]},\"active\":true}"
	    	@response = JSON.parse(RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest())
	    end
		end

		if @response
			redirect_to cdn_path
		end

	rescue TypeError => e
    flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
	rescue SocketError => e
  	flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
  end

  def deliveryUpdate
  	if params[:deliveryType].nil?
	  	@requestURI = "/v1.0/domains/#{params[:propertyId]}"
			@requestBody = "{\"originUrl\":\"#{params[:originUrl]}\",\"streamingService\":#{params[:streamingService]},\"active\":#{params[:deliveryStatus]}}"
			@response = RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest()

			if @response
				redirect_to cdn_path
			end
		elsif params[:deliveryType] == "f"
			if params[:ftpPassword].nil?
				@requestURI = "/v1.0/filedownloads/#{params[:propertyId]}"
				@requestBody = "{\"streamingService\":#{params[:streamingService]},\"active\":#{params[:deliveryStatus]}}"
			else
				@requestURI = "/v1.0/filedownloads/#{params[:propertyId]}/change_password"
				@requestBody = "{\"ftpPassword\":\"#{params[:ftpPassword]}\"}"
			end

			@response = RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest()

			if @response
				redirect_to cdn_path
			end
		end

	rescue TypeError => e
    flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
	rescue SocketError => e
  	flash[:method_error] = e.message
  	flash[:reffer_error] = "Controller: #{controller_name} - Action: #{action_name} - UUID: #{current_user.username}"
  	redirect_to errors_path
  end

  def deliveryStop
  	if params[:dtype] == "d"
  		@requestURI = "/v1.0/domains/#{params[:propertyId]}"

app/views/delivery/deliveryCreate.html.erb
<div class="portal__main-heading">
	<a href="<%= url_for(:back) %>" class="btn btn-default btn-sm ml-2">
    <span class="back_ic">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="12" viewBox="0 0 18 12">
        <path d="M353.6,392.8v2H339.4l3.6,3.6-1.4,1.4-6-6,6-6,1.4,1.4-3.6,3.6Z" transform="translate(-335.6 -387.8)" fill="#333333"/>
      </svg>
    </span>
    <span>
      Back
    </span>
  </a>
</div>
<div class="portal__main-left expanded">
	<div class="panel">
		<div class="panel__list create">
			<div class="panel__list create-notice">
				<span class="notice">To create a Website Acceleration/Large File Download, select one of the options:</span>
			</div>
			<div class="create__options-list">
				<a href="<%= cdn_create_url %>" class="create__options-list-item clearfix<% if params[:type].nil? %> active<% end %>">
					<div class="create__options-list-item-ic">
						<div class="was_ic">
							<svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 19 19">
								<path d="M816.1,426.1a.5.5,0,1,1-.5.5A.472.472,0,0,1,816.1,426.1Zm0,4a.5.5,0,1,1-.5.5A.472.472,0,0,1,816.1,430.1Zm2.3-8.2a.967.967,0,1,1-.3.7A.908.908,0,0,1,818.4,421.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,818.4,425.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,818.4,429.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,818.4,433.9Zm3.6-8.4a1.712,1.712,0,1,1-.4,1.1A1.82,1.82,0,0,1,822,425.5Zm0,4.1a1.712,1.712,0,1,1-.4,1.1A1.82,1.82,0,0,1,822,429.6Zm1.8-6.3a.967.967,0,1,1,.3-.7A.908.908,0,0,1,823.8,423.3Zm-1.4,10.6a.967.967,0,1,1-.3.7A.908.908,0,0,1,822.4,433.9Zm.7-13.8a.5.5,0,1,1,.5-.5A.472.472,0,0,1,823.1,420.1Zm0,17a.5.5,0,1,1-.5.5A.472.472,0,0,1,823.1,437.1Zm3-11.6a1.712,1.712,0,1,1-.4,1.1A1.366,1.366,0,0,1,826.1,425.5Zm0,4.1a1.712,1.712,0,1,1-.4,1.1A1.366,1.366,0,0,1,826.1,429.6Zm1.7-6.3a.967.967,0,1,1,.3-.7A.908.908,0,0,1,827.8,423.3Zm-1.4,10.6a.967.967,0,1,1-.3.7A.908.908,0,0,1,826.4,433.9Zm.7-13.8a.5.5,0,1,1,.5-.5A.472.472,0,0,1,827.1,420.1Zm0,17a.5.5,0,1,1-.5.5A.472.472,0,0,1,827.1,437.1Zm3.3-15.2a.967.967,0,1,1-.3.7A.908.908,0,0,1,830.4,421.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,830.4,425.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,830.4,429.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,830.4,433.9Zm3.7-6.8a.5.5,0,1,1,.5-.5C834.6,426.9,834.5,427.1,834.1,427.1Zm0,3a.5.5,0,1,1-.5.5A.472.472,0,0,1,834.1,430.1Z" transform="translate(-815.6 -419.1)"/></svg>
						</div>
					</div>
					<div class="create__options-list-item-info">
						<h6>Website Acceleration</h6>
						<small>Website Acceleration Description</small> 
					</div>
					<div class="create__options-list-item-arrow">
						<% if params[:type].nil? %>
						<div class="arrow_ic">
							<svg xmlns="http://www.w3.org/2000/svg" width="7.4" height="12" viewBox="0 0 7.4 12"><path d="M267.3,398.2l4.6-4.6-4.6-4.6,1.4-1.4,6,6-6,6Z" transform="translate(-267.3 -387.6)" fill="var(--main-color)"/></svg>
						</div>
						<% end %>
					</div>
				</a>
				<a href="<%= cdn_create_url %>?type=lfd" class="create__options-list-item clearfix<% if params[:type].present? %> active<% end %>">
					<div class="create__options-list-item-ic">
						<div class="lfd_ic">
							<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18"><path d="M409.6,280.4h18v18h-18Zm15.9,16v-14h-14v14Zm-9.9-8v2h-2v-2Zm3.9-4v2h-2v-2Zm0,4v2h-2v-2Zm0,4v2h-2v-2Zm4.1-4v2h-2v-2Z" transform="translate(-409.6 -280.4)""/></svg>
						</div>
					</div>
					<div class="create__options-list-item-info">
						<h6>Large File Download</h6>
						<small>Large File Download Description</small> 
					</div>
					<div class="create__options-list-item-arrow">
						<% if params[:type].present? %>
						<div class="arrow_ic">
							<svg xmlns="http://www.w3.org/2000/svg" width="7.4" height="12" viewBox="0 0 7.4 12"><path d="M267.3,398.2l4.6-4.6-4.6-4.6,1.4-1.4,6,6-6,6Z" transform="translate(-267.3 -387.6)" fill="var(--main-color)"/></svg>
						</div>
						<% end %>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>
<div class="portal__main-center primary croped">
	<div class="dashboard">
		<div class="dashboard__container">
			<div class="dashboard__container-card clearfix">
				<div class="dashboard__container-card">
					<div class="dashboard__container-card-item">
						<div class="delivery">
							<h5><% if params[:type].nil? %>Add Website Acceleration<% else %>Add Large File Download<% end %></h5>

							<% if flash[:confirm_notice] %>
		            <div class="alert alert-warning mt-3"><%= flash[:confirm_notice] %></div>
		          <% end %>

							<% if params[:type].nil? %>
								<%= form_for "", url: {action: :deliveryAdd, controller: :delivery}, method: :post, html: { class: 'mt-3', id: 'form', multipart: true } do |f|%>
									<div class="form-group">
										<%= f.label :deliveryUrl, 'Delivery Domain Name' %>
										<%= f.text_field :deliveryUrl, class: 'form-control' %>
										<small id="domainlHelp" class="form-text text-muted">Domain name can only contain lowercase letters, digits, hyphens, or periods. Please enter a valid domain name. E.g: 'www.domain.com'.</small>
									</div>

									<div class="form-group">
										<%= f.label :originUrl, 'Origin Domain/IP' %>
										<%= f.text_field :originUrl, class: 'form-control' %>
										<small id="domainlHelp" class="form-text text-muted">Origin domain name can only contain lowercase letters, digits, hyphens, or periods. Please enter a valid origin serer host name or IP. E.g: 'origin.domain.com'.</small>
									</div>

									<div class="switch-group mb-3 clearfix">
								    <label class="switch">
										  <%= f.check_box :streamingService, { class: 'custom-control-input', checked: false }, "true", "false" %>
										  <span class="slider round"></span>
										</label>
										<%= f.label :streamingService, 'Enable Streaming', class: 'switch-group-label' %>
									</div>

									<div class="text-left mt-3">
							      <%= button_tag(type: "submit", class: "btn btn-default primary btn-sm mr-3") do %>
							        Save
							      <% end %>
							      <a href="<%= cdn_url %>" class="btn btn-light btn-sm">Back</a>
							    </div>
								<% end %>
							<% elsif params[:type] == "lfd" %>
								<%= form_for "", url: {action: :deliveryAdd, controller: :delivery}, method: :post, html: { class: 'mt-3', id: 'form', multipart: true } do |f|%>
									<div class="form-group">
										<%= f.label :deliveryUrl, 'File Download Domain Name' %>
										<%= f.text_field :deliveryUrl, class: 'form-control' %>
										<small id="domainlHelp" class="form-text text-muted">File download name can only contain lowercase letters, digits, hyphens, or periods. Please enter a valid name or domain name e.g: 'lfdname' or 'lfd.domain.com'.</small>
									</div>

									<div class="form-group">
										<%= f.label :ftpPassword, 'Ftp Password' %>
										<%= f.password_field :ftpPassword, class: 'form-control' %>
										<small id="domainlHelp" class="form-text text-muted">Password must be strong e.g: include number and character, avoid using name.</small>
									</div>

									<div class="form-group">
										<%= f.label :ftpPasswordConfirm, 'Ftp Password Confirm' %>
										<%= f.password_field :ftpPasswordConfirm, class: 'form-control' %>
									</div>
									
									<div class="switch-group mb-3 clearfix">
								    <label class="switch">
										  <%= f.check_box :streamingService, { class: 'custom-control-input', checked: false }, "true", "false" %>
										  <span class="slider round"></span>
										</label>
										<%= f.label :streamingService, 'Enable Streaming', class: 'switch-group-label' %>
									</div>

									<div class="text-left mt-3">
							      <%= button_tag(type: "submit", class: "btn btn-default primary btn-sm mr-3") do %>
							        Save
							      <% end %>
							      <a href="<%= cdn_url %>" class="btn btn-light btn-sm">Back</a>
							    </div>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>