config/routes.rb
Rails.application.routes.draw do
  # Front-End
  root "default#index"

  # Account Management
  get '/account', to: "account#index"
  get '/account/detail', to: "account#detail"
  get '/account/billing', to: "account#billing"
  get '/account/password', to: "account#password"
  get '/account/notification', to: "account#notification"

  get '/account/transaction', to: "account#transaction"
  get '/account/invoice', to: "account#invoice"

  get '/account/subscription', to: "account#subscription"
  post '/account/subscription/add', to: "account#subscriptionAdd"

  get '/account/subscription/upgrade', to: "account#subscriptionUpgrade"

  patch '/account/detail/update', to: "account#detailUpdate"
  post  '/account/password/update', to: "account#passwordUpdate"
  patch '/account/notification/update', to: "account#notificationsUpdate"

  get '/account/billing/deposit', to: "account#deposit"
  post '/account/billing/depositCharge', to: "account#depositCharge"
  
  get '/account/payment', to: "account#payment"
  get '/account/payment/charge', to: "account#paymentCharge"

  post '/account/payment/verify', to: "account#paymentVerify"
  post '/account/payment/remove', to: "account#paymentRemove"

  post '/users/_session?destroy', to: "default#sessions"

  # Reseller Management
  get '/reseller', to: "reseller#index"
  get '/reseller/customer', to: "reseller#customer"
  get '/reseller/customer/create', to: "reseller#customerCreate"
  post '/reseller/customer/add', to: "reseller#customerAdd"
  get '/reseller/customer/:username', to: "reseller#customerDetail"
  get '/reseller/customer/:username/billing', to: "reseller#customerBilling"
  get '/reseller/customer/:username/transaction', to: "reseller#customerTransactions"
  get '/reseller/customer/:username/edit', to: "reseller#customerEdit"
  patch '/reseller/customer/update', to: "reseller#customerUpdate"
  delete '/reseller/customer/:username', to: "reseller#customerDelete"

  get '/reseller/package', to: "reseller#package"
  get '/reseller/package/create', to: "reseller#packageCreate"
  post '/reseller/package/add', to: "reseller#packageAdd"

  get '/reseller/subscription', to: "reseller#subscription"

  get '/reseller/configuration', to: "reseller#configuration"
  patch '/reseller/configuration/update', to: "reseller#resellerUpdate"

  # Content Delivery Network(CDN)
  get '/cdn', to: "delivery#delivery"
  get '/cdn/:propertyId/:dtype', to: "delivery#deliveryDetail"
  get '/cdn/:propertyId/:dtype/reports', to: "delivery#deliveryReport"
  get '/cdn/:propertyId/:dtype/logs', to: "delivery#deliveryLog"

  get '/cdn/:propertyId/:dtype/policies/:ptype', to: "delivery#deliveryPolicy"

  get '/cdn/:propertyId/:dtype/policies/:ptype/add', to: "delivery#deliveryAddPolicy"

  post '/cdn/:propertyId/:dtype/policies/:ptype/', to: "delivery#deliveryUpdatePolicy"

  post '/cdn/policies/create', to: "delivery#deliveryCreatePolicy"
  delete '/cdn/:propertyId/:dtype/policies/:ptype/:policyId', to: "delivery#deliveryDeletePolicy"

  get '/cdn/create', to: "delivery#deliveryCreate"
  post '/cdn/add', to: "delivery#deliveryAdd"

  get '/cdn/:propertyId/:dtype/edit', to: "delivery#deliveryEdit"

  put '/cdn/update', to: "delivery#deliveryUpdate"

  post '/cdn/:propertyId/:dtype/stop', to: "delivery#deliveryStop"
  post '/cdn/:propertyId/:dtype/start', to: "delivery#deliveryStart"
  post '/cdn/:propertyId/:dtype/delete', to: "delivery#deliveryDelete"

  # API
  namespace :api do
    scope 'v1.1', as: :v1 do
      get '/', to: "v1#index"

      # Web Acceleration Service
      get '/listDelivery', to: "v1#listDelivery"

      # File Download Acceleration
      get '/listDownload', to: "v1#listDownload"

      # Runtime Background
      get '/customerDelivery', to: "v1#customerDelivery"
      get '/customerDownload', to: "v1#customerDownload"

      post '/customerVolume', to: "v1#customerVolume"
      post '/customerStorage', to: "v1#customerStorage"

      # Check CNAME
      get '/checkCname', to: "v1#checkCname"

      # Check SSID
      post '/checkSSID', to: "v1#checkSSID"
    end
  end

  # Authenticator
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", confirmations: 'users/confirmations' }

  # Runtime Background
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  mount Sidekiq::Web, at: '/sidekiq'

  # existing paths
  match '/errors', to: "default#bugs", via: :all
  match '*path' => 'default#errors', via: :all
end

app/controllers/reseller_controller.rb
class ResellerController < ApplicationController
  before_action :authenticate_user!

  before_action :authenticate_reseller

  # Set Request Method
  before_action :post_method, only: [:customerAdd]
  before_action :delete_method, only: [:customerDelete]

  # Set End Point Request
	before_action :base_endpoint, only: [:customerAdd, :customerDelete]

  def index
    @customers = User.where(parent_uuid: current_user.username)
  end

  def customer
  	@customers = User.where(parent_uuid: current_user.username)
  end

  def customerDetail
  	@customer = User.find_by(username: params[:username])
  end

  def customerEdit
    @customer = User.find_by(username: params[:username])
  end

  def customerBilling
    @customer = User.find_by(username: params[:username])

    if @customer.credit.nil?
      @credit = 0
    else
      @credit = @customer.credit.credit_value
    end
  end

  def customerTransactions
    @customer = User.find_by(username: params[:username])

    @previousMonthWithYear = (Date.today - 1.month).strftime("%B %Y")
    @previousMonth = (Date.today - 1.month).strftime("%Y-%m")

    @thisMonth = Date.today.strftime("%Y-%m")

    @startDateOfThisMonth = Date.current.beginning_of_month.strftime("%B %d")
    @dateTodayOfThisMonth = Date.current.strftime("%d, %Y")
  end

  def customerAdd
  	@customer = User.new(customer_params)
		@uuid = customer_params["username"]

    if customer_params["password"] != customer_params["password_confirmation"]
      flash[:confirm_notice] = "Error! Confirm password not match, please check again."
      redirect_back(fallback_location: root_path)
    end

		if @customer.save
			@requestURI = "/v1.1/createCustomer/"
			@requestBody = "{\"name\":\"#{@uuid}\",\"parentId\":#{$ROOT_ID},\"type\":2,\"partnership\":1}"
			@response = JSON.parse(RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest())

			@latest = User.find_by(username: @uuid)

			@latest.update(uuid: @response["id"])

      Credit.create(user_id: @latest.id)
      Notification.create(user_id: @latest.id)

      redirect_to reseller_customer_path
		end
  end

  def customerUpdate
    @customer = User.find_by(username: customer_detail_params["username"])

    @customer.update(name: customer_detail_params["name"], phone: customer_detail_params["phone"], company: customer_detail_params["company"])
    redirect_back(fallback_location: root_path)
  end

  def customerDelete
    @customer = User.find_by(username: params[:username])

    if @customer.destroy
      @requestURI = "/v1.1/deleteCustomer/#{@customer.uuid}"
      RestAPI.new("#{@requestURI}", "#{@requestBody}").openRequest()
    end

    redirect_back(fallback_location: root_path)
  end

  def package
    @packages = Package.where(reseller: current_user.username)
  end

  def packageAdd
    @package = Package.new(package_params)
 
    if @package.save
      redirect_to reseller_package_path
    else
      render 'packageCreate'
    end
  end

  def subscription
    @subscriptions = Subscription.where(reseller: current_user.username)
  end

  def resellerUpdate
    if portal_params["domain"] == "reseller.vncdn.vn"
      flash[:verify_notice] = "Domain unavailable for use. Please check and use another domain."
      redirect_back(fallback_location: reseller_path)
    else
      if current_user.update(portal_params)
        flash[:success] = "This record has been updated successfully"
        redirect_back(fallback_location: reseller_path)
      else
        flash[:danger] = "Error! Please check again"
        render 'account'
      end
    end
  end

  private
    def authenticate_reseller
      if current_user.accountType != 2
        redirect_to root_url
      end
    end

    def customer_detail_params
      params.require(:user).permit(:username, :name, :phone, :company)
    end

    def customer_params
      params.require(:user).permit(:name, :username, :email, :parent_uuid, :password, :password_confirmation)
    end

    def package_params
      params.require(:package).permit(:name, :bwd_limit, :stg_limit, :bwd_price, :stg_price, :bwd_price_over, :stg_price_over, :reseller, :pricing)
    end

    def portal_params
      params.require(:user).permit(:domain, :logo, :color, :attachment_delete)
    end
end

app/views/reseller/index.html.erb
<div class="portal__main-left expanded">
	<div class="panel">
		<div class="panel__heading">
			<a href="<%= url_for(:back) %>" class="btn btn-default btn-sm ml-2">
		    <span class="back_ic">
		      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="12" viewBox="0 0 18 12">
		        <path d="M353.6,392.8v2H339.4l3.6,3.6-1.4,1.4-6-6,6-6,1.4,1.4-3.6,3.6Z" transform="translate(-335.6 -387.8)" fill="#333333"/>
		      </svg>
		    </span>
		    <span>
		      Back
		    </span>
		  </a>
		</div>
		<div class="panel__list main">
			<div class="main__options-list">
				<a href="<%= cdn_url %>" class="main__options-list-item clearfix<% if current_page?(cdn_url) %> active<% end %>">
					<div class="main__options-list-item-ic">
						<div class="was_ic">
							<svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 19 19">
								<path d="M816.1,426.1a.5.5,0,1,1-.5.5A.472.472,0,0,1,816.1,426.1Zm0,4a.5.5,0,1,1-.5.5A.472.472,0,0,1,816.1,430.1Zm2.3-8.2a.967.967,0,1,1-.3.7A.908.908,0,0,1,818.4,421.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,818.4,425.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,818.4,429.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,818.4,433.9Zm3.6-8.4a1.712,1.712,0,1,1-.4,1.1A1.82,1.82,0,0,1,822,425.5Zm0,4.1a1.712,1.712,0,1,1-.4,1.1A1.82,1.82,0,0,1,822,429.6Zm1.8-6.3a.967.967,0,1,1,.3-.7A.908.908,0,0,1,823.8,423.3Zm-1.4,10.6a.967.967,0,1,1-.3.7A.908.908,0,0,1,822.4,433.9Zm.7-13.8a.5.5,0,1,1,.5-.5A.472.472,0,0,1,823.1,420.1Zm0,17a.5.5,0,1,1-.5.5A.472.472,0,0,1,823.1,437.1Zm3-11.6a1.712,1.712,0,1,1-.4,1.1A1.366,1.366,0,0,1,826.1,425.5Zm0,4.1a1.712,1.712,0,1,1-.4,1.1A1.366,1.366,0,0,1,826.1,429.6Zm1.7-6.3a.967.967,0,1,1,.3-.7A.908.908,0,0,1,827.8,423.3Zm-1.4,10.6a.967.967,0,1,1-.3.7A.908.908,0,0,1,826.4,433.9Zm.7-13.8a.5.5,0,1,1,.5-.5A.472.472,0,0,1,827.1,420.1Zm0,17a.5.5,0,1,1-.5.5A.472.472,0,0,1,827.1,437.1Zm3.3-15.2a.967.967,0,1,1-.3.7A.908.908,0,0,1,830.4,421.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,830.4,425.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,830.4,429.9Zm0,4a.967.967,0,1,1-.3.7A.908.908,0,0,1,830.4,433.9Zm3.7-6.8a.5.5,0,1,1,.5-.5C834.6,426.9,834.5,427.1,834.1,427.1Zm0,3a.5.5,0,1,1-.5.5A.472.472,0,0,1,834.1,430.1Z" transform="translate(-815.6 -419.1)"/></svg>
						</div>
					</div>
					<div class="main__options-list-item-info">
						<h6>Content Delivery Service</h6>
						<small>Manage your Web Acceleration Service</small> 
					</div>
					<div class="main__options-list-item-arrow">
						<% if current_page?(cdn_url) %>
						<div class="arrow_ic">
							<svg xmlns="http://www.w3.org/2000/svg" width="7.4" height="12" viewBox="0 0 7.4 12"><path d="M267.3,398.2l4.6-4.6-4.6-4.6,1.4-1.4,6,6-6,6Z" transform="translate(-267.3 -387.6)" fill="var(--main-color)"/></svg>
						</div>
						<% end %>
					</div>
				</a>
				<a href="<%= reseller_url %>" class="main__options-list-item clearfix<% if current_page?(reseller_url) %> active<% end %>">
					<div class="main__options-list-item-ic">
						<div class="reseller_ic">
							<svg xmlns="http://www.w3.org/2000/svg" width="18" height="20" viewBox="0 0 18 20"><path d="M277.7,1115.6a2.051,2.051,0,0,1,2,2v14a2.051,2.051,0,0,1-2,2h-14a1.816,1.816,0,0,1-1.4-.6,1.974,1.974,0,0,1-.6-1.4v-14a2.051,2.051,0,0,1,2-2h1v-2h2v2h8v-2h2v2Zm-1,15v-1c0-.9-.7-1.6-2.1-2.2a9.96,9.96,0,0,0-3.9-.9,9.587,9.587,0,0,0-3.9.9c-1.3.6-2.1,1.3-2.1,2.2v1Zm-3.9-11.1a2.9,2.9,0,1,0,.9,2.1A2.878,2.878,0,0,0,272.8,1119.5Z" transform="translate(-261.7 -1113.6)"/></svg>
						</div>
					</div>
					<div class="main__options-list-item-info">
						<h6>Reseller Management</h6>
						<small>Manage Reseller</small> 
					</div>
					<div class="main__options-list-item-arrow">
						<% if current_page?(reseller_url) %>
						<div class="arrow_ic">
							<svg xmlns="http://www.w3.org/2000/svg" width="7.4" height="12" viewBox="0 0 7.4 12"><path d="M267.3,398.2l4.6-4.6-4.6-4.6,1.4-1.4,6,6-6,6Z" transform="translate(-267.3 -387.6)" fill="var(--main-color)"/></svg>
						</div>
						<% end %>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>
<div class="portal__main-center primary croped">
	<div class="dashboard">
		<div class="dashboard__heading">
			<div class="dashboard__heading-action-list">
				<div class="dashboard__heading-action-item">
					<a href="<%= reseller_customer_create_url %>" class="btn btn-sm ml-2">
						<span class="add_ic">
							<svg xmlns="http://www.w3.org/2000/svg" width="22" height="16" viewBox="0 0 22 16"><path d="M486.5,983.4h3v2h-3v3h-2v-3h-3v-2h3v-3h2Zm3.7,5.1a14.793,14.793,0,0,1,5.3-1.1,15.237,15.237,0,0,1,5.3,1.1c1.9.7,2.7,1.7,2.7,2.9v2h-16v-2C487.5,990.2,488.4,989.3,490.2,988.5Zm8.1-4.3a3.867,3.867,0,1,1,1.2-2.8A3.631,3.631,0,0,1,498.3,984.2Z" transform="translate(-481.5 -977.4)"/></svg>
						</span>
						<span>Add Customer</span>
					</a>
				</div>
			</div>
		</div>
		<div class="dashboard__container">
			<% if current_user.phone.nil? %>
      <div class="dashboard__container-message warning">
        <p><span class="alert_ic"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 20 20"><path d="M4.9,4A9.6,9.6,0,0,1,12,1a10.068,10.068,0,0,1,7.1,2.9A9.506,9.506,0,0,1,22,11a9.9,9.9,0,0,1-2.9,7.1A9.506,9.506,0,0,1,12,21,9.9,9.9,0,0,1,2,11,9.669,9.669,0,0,1,4.9,4ZM13,12V6H11v6Zm0,4V14H11v2Z" transform="translate(-2 -1)" fill="#d97917"/></svg></span><span>Please update your personal information</span></p>
      </div>
      <% end %>
			<div class="dashboard__container-card mb-3">
				<div class="dashboard__container-card-item iam">
					<div class="dashboard__container-card-item-heading">
            <h6>Support</h6>
            <span>Documentation, hotline for emergency</span>
          </div>
				</div>
			</div>
			<div class="dashboard__container-card mb-3 clearfix sync">
				<div class="dashboard__container-card-col-4">
					<div class="dashboard__container-card-item credit">
						<div class="dashboard__container-card-item-heading">
	            <h6>Credit Remaining</h6>
	            <span>Use active subscription for your customers</span>
	          </div>
						<div class="credit">
	            <div class="credit-remaining">
	              <span>Credit remaining</span>
	              <h4><%= ApplicationController::FormatNumber.new(current_user.credit.credit_value).formatCurrency() %></h4>
	            </div>
	            <div class="credit-detail clearfix">
	            	<a href="<%= account_billing_url %>">
	            		<span class="billing_ic">
	            			<svg xmlns="http://www.w3.org/2000/svg" width="19" height="18" viewBox="0 0 19 18"><path d="M205.8,1026.2v1a2.051,2.051,0,0,1-2,2h-14a1.816,1.816,0,0,1-1.4-.6,1.974,1.974,0,0,1-.6-1.4v-14a2.051,2.051,0,0,1,2-2h14a2.051,2.051,0,0,1,2,2v1h-9a1.816,1.816,0,0,0-1.4.6,1.974,1.974,0,0,0-.6,1.4v8a2.051,2.051,0,0,0,2,2Zm-9-2v-8h10v8Zm2.9-2.9a1.712,1.712,0,1,0-.4-1.1A1.366,1.366,0,0,0,199.7,1021.3Z" transform="translate(-187.8 -1011.2)"/></svg>
	            		</span>
	            		<span>View Detail</span>
	            	</a>
	            </div>
	          </div>
					</div>
				</div>
				<div class="dashboard__container-card-col-4">
					<div class="dashboard__container-card-item customer">
						<div class="dashboard__container-card-item-heading">
	            <h6>Customers</h6>
	            <span>Customers dependened on your account</span>
	          </div>
	          <div class="customer">
	          	<div class="customer-total">
	          		<span>Total customers</span>
	              <h4><%= User.where(parent_uuid: current_user.username).size %></h4>
	          	</div>
	          	<div class="customer-detail clearfix">
	          		<a href="<%= reseller_customer_url %>">
	            		<span class="customer_ic">
	            			<svg xmlns="http://www.w3.org/2000/svg" width="22" height="14" viewBox="0 0 22 14"><path d="M929.2,952a15.5,15.5,0,0,1,2.9-.4,10.6,10.6,0,0,1,2.9.4,10.276,10.276,0,0,1,2.8,1.2,2.412,2.412,0,0,1,1.3,1.9v2.5h-14v-2.5a2.2,2.2,0,0,1,1.3-1.9A8.789,8.789,0,0,1,929.2,952Zm4.9-3.3a2.9,2.9,0,1,1,.9-2.1A2.878,2.878,0,0,1,934.1,948.7Zm8,0a2.9,2.9,0,1,1,.9-2.1A2.878,2.878,0,0,1,942.1,948.7Zm-2.1,2.9a10.6,10.6,0,0,1,2.9.4,12.609,12.609,0,0,1,2.9,1.2,2.2,2.2,0,0,1,1.3,1.9v2.5h-6v-2.5a4.319,4.319,0,0,0-2-3.5Z" transform="translate(-925.1 -943.6)"/></svg>
	            		</span>
	            		<span>View All Customers</span>
	            	</a>
	          	</div>
	          </div>
					</div>
				</div>
				<div class="dashboard__container-card-col-4 disabled">
					<div class="dashboard__container-card-item-disabled"></div>
					<div class="dashboard__container-card-item ticket">
						<div class="dashboard__container-card-item-heading">
	            <h6>Tickets</h6>
	            <span>All tickets has been sent & waiting</span>
	          </div>
	          <div class="ticket">
	          	<div class="ticket-total">
	          		<span>Total tickets</span>
	              <h4>0</h4>
	          	</div>
	          	<div class="ticket-detail clearfix">
	          		<a href="<%= reseller_customer_url %>">
	            		<span class="ticket_ic">
	            			<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path d="M870.1,1045a2.051,2.051,0,0,1,2,2v12a2.051,2.051,0,0,1-2,2h-14l-4,4v-18a2.051,2.051,0,0,1,2-2Zm-7,8v-4h-2v4Zm0,4v-2h-2v2Z" transform="translate(-852.1 -1045)"/></svg>
	            		</span>
	            		<span>All Tickets</span>
	            	</a>
	          	</div>
	          </div>
					</div>
				</div>
			</div>
			<div class="dashboard__container-card">
				<div class="dashboard__container-card-item mb-3 package">
					<div class="dashboard__container-card-item-heading">
            <h6>Packages</h6>
            <span>Create & update packages</span>
          </div>
          <div class="package">
          	<div class="package-detail clearfix">
          		<a href="<%= reseller_package_url %>">
            		<span class="package_ic">
            			<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18.1" viewBox="0 0 18 18.1"><path d="M168.4,143.5a2.106,2.106,0,0,1,.5,1.3v12.5a2.051,2.051,0,0,1-2,2h-14a2.051,2.051,0,0,1-2-2V144.8a2.106,2.106,0,0,1,.5-1.3l1.4-1.7a1.426,1.426,0,0,1,1.2-.6h12a1.425,1.425,0,0,1,1.2.6Zm-15.5-.3h13.8l-.9-1h-12Z" transform="translate(-150.9 -141.2)"/></svg>
            		</span>
            		<span>Packages Management</span>
            	</a>
          	</div>
          </div>
				</div>

				<div class="dashboard__container-card-item mb-3 subscription">
					<div class="dashboard__container-card-item-heading">
            <h6>Subscriptions</h6>
            <span>Subscription dependend on your account</span>
          </div>
          <div class="subscription">
          	<div class="subscription-total">
          		<span>Total subscriptions</span>
	            <h4><%= Subscription.where(reseller: current_user.username).size %></h4>
          	</div>
          	<div class="subscription-detail clearfix">
          		<a href="<%= reseller_subscription_url %>">
            		<span class="package_ic">
            			<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18.1" viewBox="0 0 18 18.1"><path d="M168.4,143.5a2.106,2.106,0,0,1,.5,1.3v12.5a2.051,2.051,0,0,1-2,2h-14a2.051,2.051,0,0,1-2-2V144.8a2.106,2.106,0,0,1,.5-1.3l1.4-1.7a1.426,1.426,0,0,1,1.2-.6h12a1.425,1.425,0,0,1,1.2.6Zm-15.5-.3h13.8l-.9-1h-12Z" transform="translate(-150.9 -141.2)"/></svg>
            		</span>
            		<span>Subscriptions Management</span>
            	</a>
          	</div>
          </div>
				</div>

				<div class="dashboard__container-card-item package">
					<div class="dashboard__container-card-item-heading">
            <h6>Configuration</h6>
            <span>Update your reseller portal</span>
          </div>
          <div class="package">
          	<div class="package-detail clearfix">
          		<a href="<%= reseller_configuration_url %>">
            		<span class="package_ic">
            			<svg xmlns="http://www.w3.org/2000/svg" width="19.618" height="20" viewBox="0 0 19.618 20"><path d="M56.4,1160.4l2.1,1.6a.592.592,0,0,1,.1.7l-2,3.5a.445.445,0,0,1-.6.2l-2.5-1a8.152,8.152,0,0,1-1.7,1l-.4,2.6c-.1.3-.2.4-.5.4h-4a.51.51,0,0,1-.5-.4l-.4-2.6a5.852,5.852,0,0,1-1.7-1l-2.5,1a.445.445,0,0,1-.6-.2l-2-3.5a.483.483,0,0,1,.1-.7l2.1-1.6v-2l-2.1-1.6a.592.592,0,0,1-.1-.7l2-3.5a.445.445,0,0,1,.6-.2l2.5,1a8.152,8.152,0,0,1,1.7-1l.4-2.6c.1-.3.2-.4.5-.4h4a.51.51,0,0,1,.5.4l.4,2.6a5.852,5.852,0,0,1,1.7,1l2.5-1a.445.445,0,0,1,.6.2l2,3.5a.483.483,0,0,1-.1.7l-2.1,1.6v2Zm-9.9,1.5a3.625,3.625,0,1,0-1-2.5A3.317,3.317,0,0,0,46.5,1161.9Z" transform="translate(-39.091 -1149.4)"/></svg>
            		</span>
            		<span>Reseller Portal Management</span>
            	</a>
          	</div>
          </div>
				</div>
			</div>
		</div>
	</div>
</div>